Repository Lammer-FH/boutique-hotel-technikum-2024-ba, pull requests merged in 2024-06, with the labels that each got.

#17 Setup backend service
  .gitignore
  README.md
  backend/api-service/.gitignore
  backend/api-service/.mvn/wrapper/maven-wrapper.properties
  backend/api-service/HELP.md
  backend/api-service/mvnw
  backend/api-service/mvnw.cmd
  backend/api-service/pom.xml
  backend/api-service/src/main/java/at/technikum/boutique/hotel/apiservice/ApiServiceApplication.java
  backend/api-service/src/main/java/at/technikum/boutique/hotel/apiservice/bookings/BookingsController.java
  backend/api-service/src/main/java/at/technikum/boutique/hotel/apiservice/rooms/RoomsController.java
  backend/api-service/src/main/resources/api.yml
  backend/api-service/src/main/resources/application.properties
  backend/api-service/src/main/resources/application.yml
  backend/api-service/src/test/java/at/technikum/boutique/hotel/apiservice/ApiServiceApplicationTests.java
  backend/api-service/src/test/resources/application.yml
Labels: BE, infra

#32 Feature/u2/8 hotelzimmer auswahl
  app/boutique-hotel-technikum/.env.development
  app/boutique-hotel-technikum/package-lock.json
  app/boutique-hotel-technikum/package.json
  app/boutique-hotel-technikum/src/assets/img/penthouse/Bath.jpg
  app/boutique-hotel-technikum/src/assets/img/penthouse/Bed.jpg
  app/boutique-hotel-technikum/src/assets/img/penthouse/Minibar.jpg
  app/boutique-hotel-technikum/src/assets/img/penthouse/Toilet.jpg
  app/boutique-hotel-technikum/src/components/RoomOverview/RoomExtra.vue
  app/boutique-hotel-technikum/src/components/RoomOverview/RoomOverview.vue
  app/boutique-hotel-technikum/src/components/RoomOverview/TheRoomPagination.vue
  app/boutique-hotel-technikum/src/components/RoomOverview/getIconByName.ts
  app/boutique-hotel-technikum/src/components/UI/BoutiqueCalendar.vue
  app/boutique-hotel-technikum/src/components/UI/ImageDiaShow.vue
  app/boutique-hotel-technikum/src/components/UI/TheHeader.vue
  app/boutique-hotel-technikum/src/main.ts
  app/boutique-hotel-technikum/src/network/Room.ts
  app/boutique-hotel-technikum/src/network/RoomResponse.ts
  app/boutique-hotel-technikum/src/network/Rooms.ts
  app/boutique-hotel-technikum/src/router/index.ts
  app/boutique-hotel-technikum/src/store/availableRoomByPeriod.ts
  app/boutique-hotel-technikum/src/store/availableRooms.ts
  app/boutique-hotel-technikum/src/utils/CancellationTokenCreator.ts
  app/boutique-hotel-technikum/src/utils/Formatter.ts
  app/boutique-hotel-technikum/src/utils/Guard.ts
  app/boutique-hotel-technikum/src/utils/GuardAgainst.ts
  app/boutique-hotel-technikum/src/utils/GuardIs.ts
  app/boutique-hotel-technikum/src/views/AboutPage.vue
  app/boutique-hotel-technikum/src/views/HomePage/HomePage.vue
  app/boutique-hotel-technikum/src/views/ImpressumPage.vue
  app/boutique-hotel-technikum/src/views/SearchPage/SearchPeriodPage.vue
  app/boutique-hotel-technikum/src/views/SearchPage/SearchRoomPage.vue
  app/boutique-hotel-technikum/src/views/TheNavigation.vue
  app/boutique-hotel-technikum/src/views/TheSearchNavigation.vue
  app/boutique-hotel-technikum/src/vite-env.d.ts
  backend/api-service/lombok.config
  backend/api-service/pom.xml
  backend/api-service/src/main/java/at/technikum/boutique/hotel/apiservice/ApiServiceApplication.java
  backend/api-service/src/main/java/at/technikum/boutique/hotel/apiservice/config/WebConfig.java
  backend/api-service/src/main/java/at/technikum/boutique/hotel/apiservice/extras/domain/ExtraEntity.java
  backend/api-service/src/main/java/at/technikum/boutique/hotel/apiservice/hotels/domain/HotelEntity.java
  backend/api-service/src/main/java/at/technikum/boutique/hotel/apiservice/rooms/RoomsController.java
  backend/api-service/src/main/java/at/technikum/boutique/hotel/apiservice/rooms/RoomsRepository.java
  backend/api-service/src/main/java/at/technikum/boutique/hotel/apiservice/rooms/RoomsService.java
  backend/api-service/src/main/java/at/technikum/boutique/hotel/apiservice/rooms/RoomsServiceImpl.java
  backend/api-service/src/main/java/at/technikum/boutique/hotel/apiservice/rooms/domain/RoomEntity.java
  backend/api-service/src/main/java/at/technikum/boutique/hotel/apiservice/rooms/domain/RoomExtraEntity.java
  backend/api-service/src/main/java/at/technikum/boutique/hotel/apiservice/rooms/domain/RoomExtraId.java
  backend/api-service/src/main/java/at/technikum/boutique/hotel/apiservice/rooms/domain/RoomMapper.java
  backend/api-service/src/main/resources/api.yml
  backend/api-service/src/main/resources/public/images/1.jpg
  backend/api-service/src/main/resources/public/images/2.jpg
  backend/api-service/src/main/resources/public/images/3.jpg
  backend/api-service/src/main/resources/public/images/4.jpg
  backend/api-service/src/main/resources/public/images/5.jpg
  backend/api-service/src/main/resources/public/images/6.jpg
  backend/api-service/src/test/resources/application.yml
  db/data.sql
  db/schema.sql
Labels: enhancement, FE, BE

#36 Translated leftover English text to German
  app/boutique-hotel-technikum/src/views/AboutPage.vue
  app/boutique-hotel-technikum/src/views/TheNavigation.vue
Labels: bug

#35 Bugfix - Allow same day checkout and checkin during booking
  backend/api-service/src/main/java/at/technikum/boutique/hotel/apiservice/bookings/BookingsRepository.java
  backend/api-service/src/main/java/at/technikum/boutique/hotel/apiservice/rooms/RoomsRepository.java
Labels: bug, BE

#38 Feature/u4/28 zimmer reservieren small improvments
  .gitignore
  README.md
  app/boutique-hotel-technikum/.env.development
  app/boutique-hotel-technikum/.env.development.example
  app/boutique-hotel-technikum/src/assets/img/penthouse/Bath.jpg
  app/boutique-hotel-technikum/src/assets/img/penthouse/Bed.jpg
  app/boutique-hotel-technikum/src/assets/img/penthouse/Minibar.jpg
  app/boutique-hotel-technikum/src/assets/img/penthouse/Toilet.jpg
  app/boutique-hotel-technikum/src/components/BookingPeriod.vue
  app/boutique-hotel-technikum/src/components/ContactData.vue
  app/boutique-hotel-technikum/src/components/RoomOverview/RoomOverview.vue
  app/boutique-hotel-technikum/src/components/UI/BoutiqueCalendar.vue
  app/boutique-hotel-technikum/src/network/bookRoom.ts
  app/boutique-hotel-technikum/src/network/dtos/AvailabilityResponse.ts
  app/boutique-hotel-technikum/src/network/dtos/Booking.ts
  app/boutique-hotel-technikum/src/network/dtos/Room.ts
  app/boutique-hotel-technikum/src/network/dtos/RoomResponse.ts
  app/boutique-hotel-technikum/src/network/getAvailabilities.ts
  app/boutique-hotel-technikum/src/network/getRooms.ts
  app/boutique-hotel-technikum/src/router/index.ts
  app/boutique-hotel-technikum/src/stores/availableRoomByPeriod.ts
  app/boutique-hotel-technikum/src/stores/availableRooms.ts
  app/boutique-hotel-technikum/src/stores/booking.ts
  app/boutique-hotel-technikum/src/stores/customer.ts
  app/boutique-hotel-technikum/src/stores/dataStructures/CustomerInfo.ts
  app/boutique-hotel-technikum/src/utils/ContactData.ts
  app/boutique-hotel-technikum/src/utils/periodHelper.ts
  app/boutique-hotel-technikum/src/views/BookingPage/BookingOverviewPage.vue
  app/boutique-hotel-technikum/src/views/BookingPage/BookingPage.vue
  app/boutique-hotel-technikum/src/views/BookingPage/ConfirmationPage.vue
  app/boutique-hotel-technikum/src/views/BookingPage/TheBookingForm.vue
  app/boutique-hotel-technikum/src/views/ConfirmationPage.vue
  app/boutique-hotel-technikum/src/views/ImpressumPage.vue
  app/boutique-hotel-technikum/src/views/SearchPage/SearchPeriodPage.vue
  app/boutique-hotel-technikum/src/views/SearchPage/SearchRoomPage.vue
  app/boutique-hotel-technikum/src/views/TheSearchNavigation.vue
  app/boutique-hotel-technikum/src/vite-env.d.ts
  specs/api/API_specification.pdf
  specs/db/DB-Design.pdf
  specs/db/schema.sql
Labels: FE

#39 Feature/u5/advanced confirmation
  README.md
  app/boutique-hotel-technikum/src/components/BookingPeriod.vue
  app/boutique-hotel-technikum/src/components/ContactData.vue
  app/boutique-hotel-technikum/src/components/RoomOverview/RoomOverview.vue
  app/boutique-hotel-technikum/src/components/RoomOverview/TheRoomPagination.vue
  app/boutique-hotel-technikum/src/components/UI/TheHeader.vue
  app/boutique-hotel-technikum/src/router/index.ts
  app/boutique-hotel-technikum/src/stores/availableRoomByPeriod.ts
  app/boutique-hotel-technikum/src/stores/availableRooms.ts
  app/boutique-hotel-technikum/src/stores/booking.ts
  app/boutique-hotel-technikum/src/stores/customerFormData.ts
  app/boutique-hotel-technikum/src/views/AboutPage.vue
  app/boutique-hotel-technikum/src/views/BookingPage/BookingFormRow.vue
  app/boutique-hotel-technikum/src/views/BookingPage/BookingOverviewPage.vue
  app/boutique-hotel-technikum/src/views/BookingPage/BookingPage.vue
  app/boutique-hotel-technikum/src/views/BookingPage/ConfirmationPage.vue
  app/boutique-hotel-technikum/src/views/BookingPage/TheBookingForm.vue
  app/boutique-hotel-technikum/src/views/ImpressumPage.vue
  app/boutique-hotel-technikum/src/views/SearchPage/SearchPeriodPage.vue
  app/boutique-hotel-technikum/src/views/TheNavigation.vue
  backend/api-service/Dockerfile
  backend/api-service/pom.xml
  backend/api-service/src/test/resources/application.yml
  backend/db/data.sql
  backend/db/schema.sql
  backend/docker-compose-be.yaml
  backend/docker-compose-db.yaml
  db/docker-compose-db.yaml
Labels: enhancement, FE, BE

#37 Modify image path to comply with doc and fix booking date verification bug
  app/boutique-hotel-technikum/src/components/RoomOverview/RoomOverview.vue
  backend/api-service/src/main/java/at/technikum/boutique/hotel/apiservice/bookings/BookingsServiceImpl.java
  backend/api-service/src/main/resources/public/images/rooms/1.jpg
  backend/api-service/src/main/resources/public/images/rooms/2.jpg
  backend/api-service/src/main/resources/public/images/rooms/3.jpg
  backend/api-service/src/main/resources/public/images/rooms/4.jpg
  backend/api-service/src/main/resources/public/images/rooms/5.jpg
  backend/api-service/src/main/resources/public/images/rooms/6.jpg
Labels: bug, BE

#41 Refactoring/navigation guards
  app/boutique-hotel-technikum/package-lock.json
  app/boutique-hotel-technikum/package.json
  app/boutique-hotel-technikum/src/components/BookingPeriod.vue
  app/boutique-hotel-technikum/src/main.ts
  app/boutique-hotel-technikum/src/router/index.ts
  app/boutique-hotel-technikum/src/views/AboutPage.vue
  app/boutique-hotel-technikum/src/views/BookingPage/BookingOverviewPage.vue
  app/boutique-hotel-technikum/src/views/BookingPage/BookingPage.vue
  app/boutique-hotel-technikum/src/views/BookingPage/ConfirmationPage.vue
  app/boutique-hotel-technikum/src/views/BookingPage/TheBookingForm.vue
  app/boutique-hotel-technikum/src/views/HomePage/HomePage.vue
  app/boutique-hotel-technikum/src/views/ImpressumPage.vue
  app/boutique-hotel-technikum/src/views/SearchPage/SearchPeriodPage.vue
  app/boutique-hotel-technikum/src/views/SearchPage/SearchRoomPage.vue
  app/boutique-hotel-technikum/src/views/TheNavigation.vue
  app/boutique-hotel-technikum/src/views/TheSearchNavigation.vue
Labels: code improvement
