Repository Lammer-FH/boutique-hotel-technikum-2024-ba, pull requests merged in 2024-05, with the labels that each got.

#2 Add API and DB specifications
  specs/api/API_specification.pdf
  specs/api/API_specification.yaml
  specs/db/DB-Design.pdf
  specs/db/schema.sql
Labels: docs

#3 Add docker-compose, schema and initial data script
  db/data.sql
  db/docker-compose-db.yaml
  db/schema.sql
Labels: infra

#6 Hotfix - Delete unused files created by merge error
  db/data.sql.orig
  db/schema.sql.orig
Labels: bug

#4 Setup Ionic project and update docs
  README.md
  app/boutique-hotel-technikum/.browserslistrc
  app/boutique-hotel-technikum/.eslintignore
  app/boutique-hotel-technikum/.eslintrc.cjs
  app/boutique-hotel-technikum/.gitignore
  app/boutique-hotel-technikum/.vscode/extensions.json
  app/boutique-hotel-technikum/cypress.config.ts
  app/boutique-hotel-technikum/index.html
  app/boutique-hotel-technikum/ionic.config.json
  app/boutique-hotel-technikum/package-lock.json
  app/boutique-hotel-technikum/package.json
  app/boutique-hotel-technikum/public/android-chrome-192x192.png
  app/boutique-hotel-technikum/public/android-chrome-512x512.png
  app/boutique-hotel-technikum/public/apple-touch-icon.png
  app/boutique-hotel-technikum/public/browserconfig.xml
  app/boutique-hotel-technikum/public/favicon-16x16.png
  app/boutique-hotel-technikum/public/favicon-32x32.png
  app/boutique-hotel-technikum/public/favicon.ico
  app/boutique-hotel-technikum/public/mstile-150x150.png
  app/boutique-hotel-technikum/public/safari-pinned-tab.svg
  app/boutique-hotel-technikum/public/site.webmanifest
  app/boutique-hotel-technikum/src/App.vue
  app/boutique-hotel-technikum/src/components/ExploreContainer.vue
  app/boutique-hotel-technikum/src/main.ts
  app/boutique-hotel-technikum/src/router/index.ts
  app/boutique-hotel-technikum/src/theme/variables.css
  app/boutique-hotel-technikum/src/views/Tab1Page.vue
  app/boutique-hotel-technikum/src/views/Tab2Page.vue
  app/boutique-hotel-technikum/src/views/Tab3Page.vue
  app/boutique-hotel-technikum/src/views/TabsPage.vue
  app/boutique-hotel-technikum/src/vite-env.d.ts
  app/boutique-hotel-technikum/tests/e2e/fixtures/example.json
  app/boutique-hotel-technikum/tests/e2e/specs/test.cy.ts
  app/boutique-hotel-technikum/tests/e2e/support/commands.ts
  app/boutique-hotel-technikum/tests/e2e/support/e2e.ts
  app/boutique-hotel-technikum/tests/unit/example.spec.ts
  app/boutique-hotel-technikum/tsconfig.json
  app/boutique-hotel-technikum/tsconfig.node.json
  app/boutique-hotel-technikum/vite.config.ts
Labels: infra

#14 Added Ion[Element] imports to not get warns anymore
  app/boutique-hotel-technikum/src/components/AboutPageCard.vue
  app/boutique-hotel-technikum/src/components/HomePageCard.vue
  app/boutique-hotel-technikum/src/views/AboutPage.vue
  app/boutique-hotel-technikum/src/views/HomePage.vue
  app/boutique-hotel-technikum/src/views/ImpressumPage.vue
Labels: bug

#16 Setup from Composition API to Options API
  app/boutique-hotel-technikum/src/App.vue
  app/boutique-hotel-technikum/src/assets/img/Boutique-Hotel-Technikum-Croped.jpg
  app/boutique-hotel-technikum/src/assets/img/Boutique-Hotel-Technikum.jpg
  app/boutique-hotel-technikum/src/assets/img/Happy-Family.jpg
  app/boutique-hotel-technikum/src/assets/img/Panorama-View-From-Room.jpg
  app/boutique-hotel-technikum/src/assets/img/Restaurant.jpg
  app/boutique-hotel-technikum/src/assets/img/Schoenbrunn-Castle.jpg
  app/boutique-hotel-technikum/src/assets/img/Suite.jpg
  app/boutique-hotel-technikum/src/components/AboutPageCard.vue
  app/boutique-hotel-technikum/src/components/HomePageCard.vue
  app/boutique-hotel-technikum/src/main.ts
  app/boutique-hotel-technikum/src/router/index.ts
  app/boutique-hotel-technikum/src/views/AboutPage.vue
  app/boutique-hotel-technikum/src/views/HomePage.vue
  app/boutique-hotel-technikum/src/views/HomePage/HomePage.vue
  app/boutique-hotel-technikum/src/views/HomePage/HomePageCards.ts
  app/boutique-hotel-technikum/src/views/ImpressumPage.vue
  app/boutique-hotel-technikum/src/views/TabsPage.vue
  specs/api/API_specification.pdf.orig
  specs/db/DB_Design.pdf
Labels: code improvement
